In [2]:
import numpy as np
import pandas as pd
import sympy as sy

# Arreglos de numpy

In [58]:
# Generemos una arreglos ndimensaionales, ¿como podemos acceder a los elementos?
X = np.random.randint(0, 55, (6,6))
X

array([[ 3,  2, 24, 25, 37, 30],
       [30, 30, 41, 34, 33, 30],
       [31, 11, 51,  7, 44, 27],
       [45, 33, 47, 42, 39, 16],
       [10, 22, 20, 48, 28,  3],
       [12, 13, 13, 14, 41, 14]])

In [59]:
X[0]

array([ 3,  2, 24, 25, 37, 30])

In [60]:
X[0][1:4]

array([ 2, 24, 25])

In [61]:
X[0, 1:4:2]

array([ 2, 25])

In [62]:
X[2::2,::2 ]

array([[31, 51, 44],
       [10, 20, 28]])

In [63]:
# Permutaciones:

In [64]:
X

array([[ 3,  2, 24, 25, 37, 30],
       [30, 30, 41, 34, 33, 30],
       [31, 11, 51,  7, 44, 27],
       [45, 33, 47, 42, 39, 16],
       [10, 22, 20, 48, 28,  3],
       [12, 13, 13, 14, 41, 14]])

In [65]:
X[[2,1]] =X[[1,2]]

In [66]:
X

array([[ 3,  2, 24, 25, 37, 30],
       [31, 11, 51,  7, 44, 27],
       [30, 30, 41, 34, 33, 30],
       [45, 33, 47, 42, 39, 16],
       [10, 22, 20, 48, 28,  3],
       [12, 13, 13, 14, 41, 14]])

In [67]:
# Operaciones matriciales

In [68]:
X=np.array([[1,2],[3,4]])
B=np.array([[5,2],[1,4]])
np.linalg.inv(X)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [69]:
np.linalg.det(X)

-2.0000000000000004

In [70]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [71]:
X*B

array([[ 5,  4],
       [ 3, 16]])

In [72]:
X@B

array([[ 7, 10],
       [19, 22]])

In [73]:
np.matmul(X,B)

array([[ 7, 10],
       [19, 22]])

# Algunos ejemplo

```python
import numpy as np

# Producto de matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
producto = np.dot(A, B)

# Determinante de una matriz
C = np.array([[9, 2], [3, 4]])
determinante = np.linalg.det(C)

# Inversa de una matriz
D = np.array([[2, 5], [1, 3]])
inversa = np.linalg.inv(D)

# Autovalores y autovectores
E = np.array([[2, 0], [0, 3]])
autovalores, autovectores = np.linalg.eig(E)

# Resolución de sistemas de ecuaciones lineales
F = np.array([[1, 1], [1, -1]])
b = np.array([5, 1])
solucion = np.linalg.solve(F, b)


# Norma de un vector o matriz
H = np.array([1, 2, 3])
norma = np.linalg.norm(H)

# Rango de una matriz
I = np.array([[1, 2], [2, 4]])
rango = np.linalg.matrix_rank(I)

# Potencia de una matriz
J = np.array([[1, 2], [3, 4]])
potencia = np.linalg.matrix_power(J, 3)

# Descomposición SVD
G = np.array([[1, 2], [3, 4]])
U, S, V = np.linalg.svd(G)


```


# Matrices de numpy

In [74]:
M = np.matrix(X)
type(M)

numpy.matrix

In [75]:
M@M

matrix([[ 7, 10],
        [15, 22]])

In [76]:
M.T

matrix([[1, 3],
        [2, 4]])

In [77]:
type(X)

numpy.ndarray

In [78]:
np.transpose(X)

array([[1, 3],
       [2, 4]])

In [79]:
x = symbols("x")

NameError: name 'symbols' is not defined

In [80]:
Y = np.array([[x**2,sy.sin(x)],[x,x]])
q = Matrix(Y)
q

NameError: name 'x' is not defined

In [ ]:
q@q

Matrix([
[x**4 + x*sin(x), x**2*sin(x) + x*sin(x)],
[    x**3 + x**2,        x**2 + x*sin(x)]])

# Actividad:

1. Construir un programa que permita multiplicar dos matrices

2. Cosntruir un programa que permita construir una regresion lineal simple empleando lo que sigue:

3. Construir un programa que permita calcular una regresion bidimensional y hacer su representación .


Operaciones matricial con regresión lineal.

Cuando se desea hacer una regresion lineal multivariada, existen diferentes formas de realizar la regresión, una de ellas es encontrar el error cuadrático medio y miniminzar el conjunto de parámetros de la regresión emplando algún metodo de minimización, otra forma es encontrar la expresión analítica en forma matricial para enoncontrar el conjunto de parametros de la regresión. En este último caso, la regresion lineal viene dada por la siguiente expresion generalizada:


- $\Theta = (X^T X)^{-1} X^T y$

donte $\Theta$ es la matriz de parametros asociados a la regresión lineal, X la matriz de características y y los valos esperados, así, si tenemos una conjunto de datos en N dimensiones la recta, plano o hyperplano puede ser calculado como:

$Y=\Theta^T X$


En el caso de dos dimensiones, tenemos lo siguiente, Supongamos que X, y Y presentan un comportamiento lineal, y vienen dados por:


- Sea $\vec{X}=x^1, x^2, x^3, x^4, ..., x^m$
- Sea $\vec{Y}=y^1, y^2, y^3, y^4, ..., y^m$

Para determinar la ecuacion de la recta, hay que conocer los párametros $\theta_0 $, $\theta_1$, que cumplen que :   $y^{i} = \theta_1 x^{i} + \theta_0$ la anterior expresion puede ser escrita como:

\begin{equation}
\begin{bmatrix}
y^{1}\\
y^{2}\\
\vdots\\
y^{m}\\
\end{bmatrix}=
\begin{bmatrix}
\theta_0 & \theta_1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 1 & \cdots & 1 \\
x_1^{1} & x_1^{2} & \cdots & x_1^{m} \\
\end{bmatrix}
\end{equation}


Para determinar la matriz de theta entonces se puede aplicar la ecuación:

- $\Theta = (X^T X)^{-1} X^T y$

donde:
\begin{equation}
X=
\begin{bmatrix}
1 & x_1^{1} \\
1 & x_1^{2} \\
\vdots & \vdots \\
1 & x_1^{m}
\end{bmatrix}
\end{equation}

y


\begin{equation}
y=
\begin{bmatrix}
y^1 \\
y^2 \\
\vdots\\
y^m
\end{bmatrix}
\end{equation}

Su tarea será construir un programa que realice la regresión lineal para los siguientes puntos:
```python
N = 10
x1 = np.linspace(0, 10, N)
noise=2*np.random.random(N)-1
y = 0.9*x1 + noise
```



Generalice para el siguiente problema bidimensional:


```python
N = 10
x1 = np.linspace(-1, 1, N)
x2 = np.linspace(-2, 2, N)
noise1=2*np.random.random(N)-1
noise2=2*np.random.random(N)-1
y = 2*(x1+noise1) - 3*(x2+noise2) + 0.0 #+ 4*np.random.random(100)

N = 10
X1, X2 = np.meshgrid(x1,x2)
Y = 2*X1 - 3*X2 + 0.0
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
surf = ax.plot_surface(X1, X2, Y)
#scatter = ax.scatter(x1, x2, y,"-")
```



4. Construir un programa que permita realizar eliminacion de Gauss- Jordan de una matriz

